function AdvisoryReport({ rul, uncertainty, status }) {
  const isCritical = status === 'CRITICAL'
  const isWarning = status === 'WARNING'
  const isSafe = !isCritical && !isWarning

  const getStatusColor = () => {
    if (isCritical) return '#ff6f83'
    if (isWarning) return '#ffca66'
    return '#7ef2b8'
  }

  const getRecommendation = () => {
    if (isCritical) return {
      action: 'IMMEDIATE GROUNDING REQUIRED',
      detail: `This engine has exceeded safe operational RUL thresholds. Based on LSTM analysis of the 30-cycle sensor window, degradation has reached a critical phase. Schedule an emergency shop visit and borescope inspection of the High Pressure Turbine (HPT) within the next 2 flight cycles. All operational missions must be suspended until a qualified Level-3 inspection is completed and signed off.`
    }
    if (isWarning) return {
      action: 'SCHEDULE PREVENTIVE MAINTENANCE',
      detail: `Thermal and vibration channel anomalies have been detected in the last 10 cycles. The LSTM model has identified a degradation elbow pattern consistent with early-stage High Pressure Compressor (HPC) blade erosion. Recommend grounding within 10–15 cycles and performing a full borescope and oil-debris analysis before the next long-haul mission.`
    }
    return {
      action: 'CONTINUE NORMAL OPERATIONS',
      detail: `Engine telemetry is within nominal operating range across all 21 sensor channels. No anomalous thermal drift, pressure drop, or vibration spikes have been detected in the current 30-cycle window. Proceed with scheduled mission profile. Next routine inspection due in 50 operational cycles per Rolls-Royce MRO Schedule RR-2026-C1.`
    }
  }

  const getTechnicalSolution = () => {
    if (isCritical) return `• Primary Action: Complete overhaul of the turbine assembly including replacement of worn bearing seals, tip clearance restoration, and combustor liner inspection.\n• Secondary Action: Full FADEC recalibration and test-cell acceptance run required before return to service.\n• Part Numbers: Bearing Seal RR-BS-7721, HPT Blade Set RR-HPT-B3 (pending availability confirmation).`
    if (isWarning) return `• Primary Action: Recalibration of EGT sensor offsets and proactive replacement of the air-oil heat exchanger to arrest thermal drift.\n• Secondary Action: Vibration damper inspection (HPC Stage 3–5) and oil filter analysis for metallic particle contamination.\n• Estimated Downtime: 36–48 hours. Return to service after test-cell engine run and sign-off.`
    return `• No intervention required at this time.\n• Recommended: Continue standard oil sampling at 500-cycle intervals.\n• Monitor vibration channel RMS trend — if standard deviation exceeds 0.15 over 5 consecutive cycles, escalate to Warning protocol.\n• Next scheduled A-check: ${new Date(Date.now() + 50 * 86400000).toLocaleDateString()}.`
  }

  const rec = getRecommendation()
  const sol = getTechnicalSolution()
  const statusColor = getStatusColor()

  return (
    <article className="advisory-panel panel" style={{ borderTop: `3px solid ${statusColor}` }}>
      <div className="advisory-header">
        <div>
          <span className="eyebrow gold">Maintenance Advisory Report</span>
          <h2 className="advisory-title">Aero-Engine Solution & Analysis</h2>
        </div>
        <div className="advisory-badge" style={{ background: `${statusColor}20`, color: statusColor, border: `1px solid ${statusColor}40` }}>
          {status}
        </div>
      </div>

      <div className="advisory-grid">
        <div className="advisory-section">
          <h3 style={{ color: statusColor }}>Fleet Analysis</h3>
          <p>
            This engine has <strong>{Math.round(rul)} cycles of Remaining Useful Life (RUL)</strong> based on a 
            30-cycle telemetry window processed through the Bidirectional LSTM model. Stochastic MC Dropout 
            inference (20 passes) yielded an uncertainty of <strong>±{uncertainty?.toFixed(1)} cycles</strong>, 
            providing a conservative maintenance window of <strong>{Math.max(0, Math.round(rul - 1.96 * (uncertainty || 5)))} cycles</strong> (95% lower bound).
          </p>
        </div>

        <div className="advisory-section">
          <h3 style={{ color: statusColor }}>Operational Recommendation</h3>
          <p className="advisory-action-label">{rec.action}</p>
          <p>{rec.detail}</p>
        </div>

        <div className="advisory-section advisory-solution">
          <h3 style={{ color: statusColor }}>Technical Solution & Part Actions</h3>
          <div className="solution-points">
            {sol.split('\n').map((line, i) => line.trim() && (
              <p key={i} className="solution-line">{line}</p>
            ))}
          </div>
        </div>
      </div>

      <div className="advisory-footer">
        <small>Generated by Rolls-Royce AI Intelligence System • {new Date().toLocaleString()} • Engine Session: RR-AI-2026</small>
        <button className="secondary-button" onClick={() => window.print()}>Export PDF Report</button>
      </div>
    </article>
  )
}

export default AdvisoryReport
